# Generated by Django 4.2.19 on 2025-02-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'information', 'verbose_name_plural': 'Informations'},
        ),
    ]
